# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
# https://copier.readthedocs.io/en/stable/updating/#never-change-the-answers-file-manually
_commit: v2.0.4
_src_path: gh:FallingColors/hexdummy
advanced: false
description: Hextest addon for Hex Casting
display_name: Hextest
github_repo: hextest
github_user: BreezeTheCat
java_package: io.github.breezethecat.hextest
mappings_name: Mojmap
minecraft_version_in_mod_version: true
mod_version: 0.1.0
modid: hextest
